steps:

#Decrypt App Secrets
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=otherly-love-main
  - --key=cloudbuild-env

# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Test
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'test']

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

# Deploy
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'deploy']
